### ISSUE TITLE
Documentation bug: Name description of application appears wrong

### ISSUE THREAD

**Issue by dhorne** [gryphonshafer/Bible-OBML#1]
The POD NAME is as follows

> =head1 NAME
> 
> Bible::OBML - Manipulate Google/GMail Tasks

I don't believe this module is designed for Google/Gmail - perhaps pasteage from Google::Tasks?

**Comment by gryphonshafer** [comment]
heh, good point. Thanks for the report.

**Comment by gryphonshafer** [comment]
Resolved with 5c46fd1, v1.05.
