### ISSUE TITLE
Why limit to ASCII?

### ISSUE THREAD

**Issue by perlancar** [gryphonshafer/Bible-OBML#4]
The doc says:

> OBML is a pure-ASCII-text markup way to represent Bible content, one whole text file per chapter. The goal or purpose of OBML is similar to Markdown in that it provides a human-readable text file allowing for simple and direct editing of content while maintaining context, footnotes, cross-references, "red text", and quotes.

I see in the source code that you're already opening the file with utf8.

**Comment by gryphonshafer** [comment]
Yeah, good point. There's no reason to restrict to ASCII, plus a few reasons not to.

**Comment by gryphonshafer** [comment]
Fixed in v1.07
