### ISSUE TITLE
missing "use Carp;" in OBML.pm

### ISSUE THREAD

**Issue by viy2** [gryphonshafer/Bible-OBML#5]
OBML.pm does not pass a syntax check using perl -c:
...
Subroutine new redefined at /usr/src/tmp/perl-Bible-OBML-buildroot/usr/share/perl5/Bible/OBML.pm line 23.                                                       
String found where operator expected at /usr/src/tmp/perl-Bible-OBML-buildroot/usr/share/perl5/Bible/OBML.pm line 35, near "croak "Unable to read file $filename; $!""                                                                          
        (Do you need to predeclare croak?)                                      
String found where operator expected at /usr/src/tmp/perl-Bible-OBML-buildroot/usr/share/perl5/Bible/OBML.pm line 41, near "croak "Unable to write file $filename; $!""                                                                         
        (Do you need to predeclare croak?)                                      
syntax error at /usr/src/tmp/perl-Bible-OBML-buildroot/usr/share/perl5/Bible/OBML.pm line 35, near "croak "Unable to read file $filename; $!""

**Comment by gryphonshafer** [comment]
Bible::OBML uses [exact](https://metacpan.org/pod/exact), which supplies croak to the Bible::OBML namespace. The following passes a syntax check using perl -c:

    #!/usr/bin/env perl
    use Bible::OBML;

**Comment by viy2** [comment]
Well, this look like a strange behavior of perl -c.
Either this is a bug in perl -c and it should be reported to perl core team,
however unlikely, for perl -c works for a script
use exact;
croak "I work!";

or this is a feature of perl -c that related to the circular dependency 
Bible/OBML.pm -> Bible/OBML/HTML.pm -> Bible/OBML.pm
(circular dependency does not look good too)

either way there is a problem upgrading
http://autoperl.altlinux.org/pub/ALTLinux/cpanbuilder/Sisyphus/files/SRPMS/perl-Bible-OBML-1.12-alt1.src.rpm
to fresh versions, because of mandatory perl -c syntax check.

If you do not want to resolve the circular dependency
consider simply adding
use Carp;
as this does help to pass the syntax check.

perl -Ilib -c lib/Bible/OBML.pm 
Subroutine new redefined at lib/Bible/OBML.pm line 24.
Subroutine read_file redefined at lib/Bible/OBML.pm line 34.
Subroutine write_file redefined at lib/Bible/OBML.pm line 40.
Subroutine parse redefined at lib/Bible/OBML.pm line 47.
Subroutine render redefined at lib/Bible/OBML.pm line 239.
Subroutine smartify redefined at lib/Bible/OBML.pm line 334.
Subroutine desmartify redefined at lib/Bible/OBML.pm line 446.
Subroutine canonicalize redefined at lib/Bible/OBML.pm line 452.
lib/Bible/OBML.pm syntax OK

consider this as compatibility with more environments.

**Comment by viy2** [comment]
Thanks, built successfully, see
http://autoimports.altlinux.org/pub/ALTLinux/autoimports/Sisyphus/files/SRPMS/perl-Bible-OBML-1.17-alt1.src.rpm
